parameters:
    pim_datagrid.product.attribute_type.idrolab_brand:
        column:
            type:        flexible_option
            selector:    flexible_option
        filter:
            type:        flexible_choice
            parent_type: ajax_choice
            options:
                field_options:
                    multiple: true
        sorter:          flexible_field

services:
    idrolab_catalog.attributetype.brand:
        class: '%pim_custom_entity.attribute_type.custom_option_simple_select.class%'
        arguments:
            - brand
            - pim_ajax_entity
            - '@pim_catalog.validator.constraint_guesser.chained_attribute'
            - idrolab_catalog_brand
            - Idrolab\Bundle\CatalogBundle\Entity\Brand
        tags:
            - { name: pim_catalog.attribute_type, alias: idrolab_catalog_brand, entity: '%pim_catalog.entity.product.class%' }

    pim_catalog.attributetype.packaging_collection:
        class: Idrolab\Bundle\CatalogBundle\AttributeType\PackagingCollectionType
        arguments:
            - packagings
            - idrolab_enrich_packaging_collection
            - '@pim_catalog.validator.constraint_guesser.chained_attribute'
        tags:
            - { name: pim_catalog.attribute_type, alias: idrolab_catalog_packaging_collection, entity: %pim_catalog.entity.product.class% }
